apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapi
  namespace: rapi
  labels:
    app: rapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rapi
  template:
    metadata:
      labels:
        app: rapi
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: rapi
          image: dex-registry:5000/rapi:latest # image in your k3d registry
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # your appâ€™s exposed port
          resources:
            limits:
              memory: "128Mi"
            requests:
              cpu: "10m"
              memory: "128Mi"
          env:
            - name: PORT
              value: "8080"
            - name: GRPC_ADDRESS
              value: "http://grpcapi.grpcapi.svc.cluster.local:50051"
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 3000
          #   initialDelaySeconds: 15
          #   periodSeconds: 20
