[package]
name = "rapi"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rapi"

[dependencies]
axum = { version = "0.8.6" }
prost = "0.14.1"
tokio = { version = "1.48.0", features = ["rt-multi-thread"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
tonic-prost-build = "0.14.2"
