apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.15.2 # adjust to latest version
    helm:
      releaseName: metallb
      values: |
        controller:
          logLevel: info
        speaker:
          logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
