---
apiVersion: v1
kind: Service
metadata:
  name: grpcapi
  namespace: grpcapi
  labels:
    app: grpcapi
spec:
  type: ClusterIP
  selector:
    app: grpcapi
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
